export const GET_LIST_START = "GET_LIST_START"
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS"
export const GET_LIST_ERROR= "GET_LIST_ERROR"

export const POST_LIST_START = "POST_LIST_START"
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS"
export const POST_LIST_ERROR = "POST_LIST_ERROR"

export const DELETE_LIST_START = "DELETE_LIST_START"
export const DELETE_LIST_SUCCESS= "DELETE_LIST_SUCCESS"
export const DELETE_LIST_ERROR = "DELETE_LIST_ERROR"

export const POST_TASK_START = "POST_TASK_START"
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS"
export const POST_TASK_ERROR = "POST_TASK_ERROR"

export const DELETE_TASK_START = "DELETE_TASK_START"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_ERROR  = "DELETE_TASK_ERROR "

export const PATCH_TASK_START = "PATCH_TASK_START"
export const PATCH_TASK_SUCCESS = "PATCH_TASK_SUCCESS"
export const PATCH_TASK_ERROR = "PATCH_TASK_ERROR"

export const CHECK_TASK_START = "CHECK_TASK_START"
export const CHECK_TASK_SUCCESS = "CHECK_TASK_SUCCESS"
export const CHECK_TASK_ERROR = "CHECK_TASK_ERROR"
